# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linting

on:
  push:
    branches: [ master, currency-system, database-gateways ]
  pull_request:
    branches: [ master, currency-system, database-gateways ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npx linting
      run: |
        npm run build --if-present
        npm install
        npx eslint .
      env:
        CI: true
