name: Node CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: npm install, build, and test
      run: |
        npm ci
        npm install
        npx eslint .
      env:
        CI: true
